name: Publish Docker

on: [push]

jobs:
  alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["7.4", "7.3", "7.2", "7.1", "7.0", "5.6", "5.5"]
    steps:
      - uses: actions/checkout@master
      - name: Build PHP ${{ matrix.version }} Alpine and publish to DockerHub Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: mileschou/xdebug:${{ matrix.version }}
          username: mileschou
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerfile: ${{ matrix.version }}/Dockerfile

  apache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["7.4", "7.3", "7.2", "7.1", "7.0", "5.6", "5.5"]
    steps:
      - uses: actions/checkout@master
      - name: Build PHP ${{ matrix.version }} Apache and publish to DockerHub Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: mileschou/xdebug:${{ matrix.version }}-apache
          username: mileschou
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerfile: ${{ matrix.version }}/apache/Dockerfile
